### ISSUE TITLE
Explanation of "unfixed"

### ISSUE THREAD

**Issue by franchesoni** [volotat/ARC-Game#2]
Hi! I wonder what are the unfixed levels. They seem interesting, but for some what seems to me the obvious solution doesn't work. 

What is the reason behind the naming of the category?

**Comment by volotat** [comment]
Some tasks in ARC dataset contains mistakes. I moved them into "unfixed" cathegory to fix them later. I already fixed some of them and propose fixes to the original ARC dataset as well. I will made list of modified levels later.
