### ISSUE TITLE
Easy 8FBCA751 has multiple solutions.

### ISSUE THREAD

**Issue by Erquint** [volotat/ARC-Game#5]
![Supposedly incorrect solution.](https://user-images.githubusercontent.com/4364856/189914748-3069fe2b-4940-45e9-94be-04e43741edb9.png)
I can't see what would make this solution incorrect.
The islands are rectangular, spaced apart and the input shapes are copied verbatim sans background.
Unless you're willing to point out something I missed, would you consider moving this to the multiple solutions category?

**Comment by Erquint** [comment]
Perhaps there's a rule implied that islands have to touch corners, but none of the examples make that decidable. The second one comes closest, but there is no other way to solve it even without this implied rule, so it's not really showcasing the rule distinction.

**Comment by volotat** [comment]
Exactly the issue I pointed out earlier in the original repository: https://github.com/fchollet/ARC-AGI/issues/84 . As François stated "This is an acceptable level of ambiguity", so it is fine.
