### ISSUE TITLE
Question on difficulty

### ISSUE THREAD

**Issue by iamseungpil** [volotat/ARC-Game#7]
Hello. I'm curious about the criteria used for difficulty classification in the ARC-Game project. Is there a specific classification standard?

**Comment by volotat** [comment]
There is no criteria, just a subjective experience I had while solving the task. Even more so, I suspect that to determine how hard the task is is equivalent to solving the task  and therefore a metric that could measure a difficulty of the task objectively might be created if and only there is a general algorithm for solving the tasks. For example the length of the minimal program that solves the task might be such a criteria, but you can imagine that to generate such a program you have to solve ARC first.
